colunas:
- '% Iron Feed'
- '% Silica Feed'
- Starch Flow
- Amina Flow
- Ore Pulp Flow
- Ore Pulp pH
- Ore Pulp Density
- Flotation Column 01 Air Flow
- Flotation Column 02 Air Flow
- Flotation Column 03 Air Flow
- Flotation Column 04 Air Flow
- Flotation Column 05 Air Flow
- Flotation Column 06 Air Flow
- Flotation Column 07 Air Flow
- Flotation Column 01 Level
- Flotation Column 02 Level
- Flotation Column 03 Level
- Flotation Column 04 Level
- Flotation Column 05 Level
- Flotation Column 06 Level
- Flotation Column 07 Level
- '% Iron Concentrate'
- '% Silica Concentrate'
features:
- '% Iron Feed'
- '% Silica Feed'
- Starch Flow
- Amina Flow
- Ore Pulp Flow
- Ore Pulp pH
- Ore Pulp Density
- Flotation Column 01 Air Flow
- Flotation Column 02 Air Flow
- Flotation Column 03 Air Flow
- Flotation Column 04 Air Flow
- Flotation Column 05 Air Flow
- Flotation Column 06 Air Flow
- Flotation Column 07 Air Flow
- Flotation Column 01 Level
- Flotation Column 02 Level
- Flotation Column 03 Level
- Flotation Column 04 Level
- Flotation Column 05 Level
- Flotation Column 06 Level
- Flotation Column 07 Level
iron_concentrate: '% Iron Concentrate'
rawdata_filename: MiningProcess_Flotation_Plant_Database.csv
target_prediction: '% Silica Concentrate'
