apiVersion: v1
kind: Service
metadata:
  name: miningqualitypredicition-api-service
spec:
  selector:
    app: miningqualitypredicition-api
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
  type: LoadBalancer